
DROP TABLE IF EXISTS alerts;
DROP TABLE IF EXISTS config;

CREATE TABLE alerts (
       id INTEGER PRIMARY KEY AUTOINCREMENT,
       timestamp INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP,
       updated INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP,
       expiry INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP,
       type TEXT NOT NULL DEFAULT "Unknown",
       severity INTEGER NOT NULL DEFAULT 0,
       source INTEGER NOT NULL DEFAULT 0,

       headline TEXT NULL,
       subtitle TEXT NULL,
       icon TEXT NULL,
       nowrap BOOLEAN NULL
);

CREATE TABLE nodes (
    id  TEXT PRIMARY KEY,
    last_ip TEXT NOT NULL,
    last_contact_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    type TEXT
);

CREATE TABLE config (
    id TEXT PRIMARY KEY,
    value TEXT NULL DEFAULT NULL,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
